name: Deploy to GitHub Pages

on:
  push:
    branches: [released]
  workflow_dispatch: # manual trigger

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name:
        uses: withastro/action@v3
        env:
          PUBLIC_API_URL: ${{ vars.PUBLIC_API_URL }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
