name: gatsby-build-and-publish
run-name: Build Gatsby static site and publish to live branch
on:
  push:
    branches:
      - released
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: |
          npm install -g gatsby-cli
          npm install -g gh-pages
          npm install
      - name: Clean and build
        run: |
          gatsby clean
          gatsby build
      - name: Publish to live
        run: gh-pages -d public -b live -u "$(git log -n 1 --pretty=format:%an) <$(git log -n 1 --pretty=format:%ae)>"
