name: publish-website
on:
  push:
    branches:
      - released
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g gatsby-cli
      - run: npm install -g gh-pages
      - run: gatsby clean
      - run: gatsby build
      - run: gh-pages -d public -b live